sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
  - secure: G4QFYOQXq4tKUYW7oCI0WnI61AumhAkvMyDdTW3RgefG6QeJa67fgx3FRJp0yVbFZQEBXoW5e79mIrVC8BO+3rr4NzdlxHFTlV9c1C1hgIiQFIl+fDEz+T7+5tKFuIWP0PNqpD1dJM+en3Gm+ppFXXiSQ5lN7eUiX+hik4Bo5nIH4Slrg07TmhICpbhzYb6AySOi/X9yfV+LkkE8SS4JwjyZkf12qP86mHBTqXDBlYUclP17VgoZC1jCDAPZSJAZ0tqb7fj76e4nwm4EWrUg1wYUbfq6XO5PZ1GfnorFCAsQNfCjD2hND1k38MNGD4OuMbSvdE5IlL36hypcWVFx+CBVbgcGUYL/CWw0+2NI/BLHgE8Sbmg3NtJZ7QJFW9w7bKESL3jt13CaHE+SuRDtescDwTWTQYPhZWBnRBKGW5JgFifKNYyl6htDWMvAEGJKPO1/ShHzOhCeXfTu6TgHFeqfMRjLPEFSBasmouPasFue5W4vpHHRjaktPCMR7XQ1AFniYW9z8/o5kv+0JD3fsiJpXjGiT9SOI3RdV+2UwkjDWaby2GxAiJhwXzJ3KpJXbRd5Vbede6UoxmJCeuflWjaT4X4kuHGfHdFA8v0XJop8tSHQiJYzei3laknGClgNgON4JZEuiQy/S+lOOCF4UZJp2059VrmpJz6q+e09DRE=
  - secure: LY/h2OA43RIq1+FaFs+uWId5eCa/onOByna0OyQyg+xJ9Cm6tlXy1FIawVOi7zRTxNmCJwXrSNqxJ9X+xxS6eH4wP6aOhmARIiiPEH9cN4KOpWYevIAW+GUBG5anjMsSREWIriGeDwDsauaQejrVWXISI3SfKSOz6omU1NxMybQQHBCCJqQAMx36MRul/34dKnEKC9JEcQhJK/Y7h4G2lB7ifvI6l861qZQs6rKdeRWI/HJr2Zg+MWsQQ2ADaQOp+g9gLXxfGhJeLzhBsuHAV2gCPjRxAbZhz+yYnGTfm3bMY6v0kKmx3c+wQYiokhpElGD1qL9HtnizQ2bGknd4lfDPLlzcoOIvwcpIQKVVDuHMe/5kL5hYre1B5FDf2IkS386bNa209VMlVmL5JpdPV6jBOwR13bA9fnAjXCE7lWoPtVvHRLJDXvB4vK3Cdp+Rt4ca8EI/aNcHDRIh6OP4V14aAH0pFgMlzLjJvLx1mt4XIrqf38i0dHzntFjVNqus/a121OFWw14QsrS5Fk0dFdfQRAtOcQnogXheL+RjL2n0lkpUSZbJk610pX3UIaPgeFS9NjPPrf7nunMvT5LanMwjThO0cf7zuVrJ0zMT0lolrDGjpoU6hYItvQF7rAXFyTkzFKSSuaLotVCeSqnS9+1LaqrblhlbyIQ7CGjdmhk=
before_install:
- openssl aes-256-cbc -K $encrypted_da0ee7500877_key -iv $encrypted_da0ee7500877_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
